talk: client.c client.h list.c list.h monitor.h monitor.c receiver.c sender.c writer.c reader.c
	gcc -pthread -o s-talk client.c list.c monitor.c receiver.c sender.c writer.c reader.c

clean:
		rm s-talk
